Repository ProjectKinni/kkini-frontend, pull requests merged in 2023-09, with the labels that each got.

#10 [KN-140] Review View 추가
  README.md
  package-lock.json
  package.json
  src/components/Header.js
  src/components/ReviewCard.js
  src/components/ReviewList.js
Labels: enhancement

#11 [KN-136] Filtering 기능 컴포넌트 분리
  .gitignore
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-08-008_PM_6_55_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-08-008_PM_6_55_[Changes]1/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-08-008_PM_6_55__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-08-008_PM_6_55__Changes_1.xml
  .idea/workspace.xml
  READMD.md
  src/App.css
  src/components/Categories.js
  src/components/Filters.js
  src/components/Header.js
  src/components/KkiniChecked.js
  src/components/Logo.js
  src/components/NavButtons.js
  src/components/NavigationBar.js
  src/components/ProductDetail.js
  src/components/ProductList.js
  src/components/ProductNutrition.js
  src/components/SearchBar.js
  src/components/UseCategoryFromSearchParams.js
  src/components/UseFetchProducts.js
  src/components/UseSearchResults.js
  src/containers/CategoryBarContainer.js
  src/containers/NavigationBarContainer.js
  src/containers/ProductDetailContainer.js
  src/pages/MainPage.js
  src/pages/ProductDetailPage.js
  src/pages/SearchResultPage.js
  src/styles/MainPage.css
  src/styles/SearchResultPage.css
  src/utils/ApiClient.js
Labels: documentation

#12 [KN-140] Filtering 기능 버그 픽스
  .idea/.gitignore
  .idea/kkini-frontend.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-08-008_PM_6_55_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-08-008_PM_6_55_[Changes]1/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-08-008_PM_6_55__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-08-008_PM_6_55__Changes_1.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/pages/SearchResultPage.js
  src/utils/ApiClient.js
Labels: bug

#13 [KN-175]검색 기능 수정
  .gitignore
  src/components/ProductDetail.js
  src/components/ProductList.js
  src/components/UseSearchResults.js
  src/pages/ProductDetailPage.js
  src/pages/SearchResultPage.js
  src/utils/ApiClient.js
Labels: fix

#14 [KN-174] 상품 상세 페이지 & 이용 약관 & 개인정보처리 구현
  src/App.js
  src/components/Footer.js
  src/components/ProductDetail.js
  src/components/ProductNutrition.js
  src/pages/PrivacyPolicyPage.js
  src/pages/ProductDetailPage.js
  src/pages/TermsOfServicePage.js
Labels: feat

#15 [KN-179] feat: Introduction and Help Structure
  package-lock.json
  package.json
  src/App.js
  src/assets/images/Green.png
  src/assets/images/Pick.png
  src/assets/images/Rank.png
  src/components/Help.js
  src/components/Information.js
  src/containers/NavigationBarContainer.js
  src/pages/HelpPage.js
  src/pages/InformationPage.js
Labels: feat

#16 [KN-176] 로그인 상태로 제품 상세 페이지에서 Review Create 기능 추가
  src/App.js
  src/assets/images/banner_image.png
  src/components/BannerAd.js
  src/components/ProductNutrition.js
  src/components/ReviewCard.js
  src/components/ReviewForm.js
  src/components/ReviewList.js
  src/pages/ProductDetailPage.js
  src/styles/MainPage.css
Labels: feat

#29 [KN-195] feat: ProductLike
  .idea/misc.xml
  src/components/HandleLogoutButton.js
  src/components/LikedProductItem.js
  src/components/LikedProductList.js
  src/components/ProductDetail.js
  src/components/ProductLikeButton.js
  src/components/ShowUserInfo.js
  src/components/ToggleLike.js
  src/components/UseFetchLikedProducts.js
  src/components/UseRemoveLike.js
  src/containers/NavigationBarContainer.js
  src/pages/MyPage.js
  src/pages/ProductDetailPage.js
Labels: feat

#30 [KN-195] feat: Add Liked Button to Product List
  src/components/ProductList.js
Labels: feat

#32 [KN-198] 조회수 구현 완료
  src/App.js
  src/components/GetUserInfo.js
  src/components/ProductDetail.js
  src/components/ProductList.js
  src/containers/ProductDetailContainer.js
  src/pages/ProductDetailPage.js
  src/utils/ApiClient.js
Labels: feat

#37 [KN-197] feat: MyPage ReviewList
  src/components/LikedProductList.js
  src/components/ReviewListForMypage.js
  src/components/UseUserReviews.js
  src/pages/MyPage.js
  src/utils/ApiClient.js
Labels: feat

#41 [KN-195] fix: Paging My Page LikeList
  src/components/LikeListForMypgae.js
  src/components/LikedProductItem.js
  src/components/LikedProductList.js
  src/components/ReviewListForMypage.js
  src/components/ShowUserInfo.js
  src/components/UseRemoveLike.js
  src/pages/MyPage.js
  src/utils/ApiClient.js
Labels: fix

#43 [KN-196] Review 사진 업로드/출력, ReviewCount View
  package-lock.json
  package.json
  src/components/Filters.js
  src/components/ProductDetail.js
  src/components/ProductList.js
  src/components/ReviewCard.js
  src/components/ReviewForm.js
  src/components/ReviewList.js
  src/pages/CommunityPage.js
  src/pages/ProductDetailPage.js
  src/pages/SearchResultPage.js
  src/styles/ProductDetail.css
  src/utils/ApiClient.js
Labels: feat

#46 [마이페이지] 하단 탭, 데이터 없을 때 메시지 퍼블리싱 적용
  src/components/LikeListForMypgae.js
  src/pages/MyPage.js
  src/styles/MyPage.css
Labels: feat

#47 [Kn-198] 끼니 Pick 추천 로직 구현
  src/components/mainPage/MainSliderSection.js
  src/components/mainPage/ProductSlickSlider.js
  src/components/mainPage/ProductSlide.js
  src/pages/KkiniPickPage.js
  src/utils/ApiClient.js
Labels: feat

#51 [KN-196] Add infinite scroll
  src/components/ReviewForm.js
  src/components/ReviewList.js
  src/components/UseSearchResults.js
  src/utils/ApiClient.js
Labels: feat
